name: Deploy to cPanel via FTP

on:
  push:
    branches:
      - main # O deploy acontecerá automaticamente sempre que houver um push na branch main

jobs:
  web-deploy:
    name: Build & Deploy to cPanel
    runs-on: ubuntu-latest
    steps:
    - name: Checkout do Repositório
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Instalar Dependências
      run: npm install

    - name: Gerar Build (dist)
      run: npm run build

    - name: Realizar Deploy via SCP (SSH)
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        port: 22
        source: "./dist/*"
        target: "/public_html/fieb2026/"
        strip_components: 1 # Isso remove a pasta 'dist' do caminho final
