name: Deploy to cPanel via SFTP

on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: Build & Deploy to cPanel
    runs-on: ubuntu-latest
    steps:
    - name: Checkout do Repositório
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Instalar Dependências
      run: npm install

    - name: Gerar Build (dist)
      run: npm run build

    - name: Realizar Deploy via SFTP para o cPanel
      uses: wlixcc/SFTP-Deploy-Action@v1.2.4
      with:
        host: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        port: 22
        local_path: './dist/*'
        remote_path: '/public_html/fieb2026/'
        # Nota: Se o seu IP estiver correto nas Secrets, 
        # o SFTP usará a porta 22 para ignorar bloqueios comuns de FTP.
